<a href="https://colab.research.google.com/github/SaurabhSRP/04-NLP-based-Projects/blob/main/SMS%20Spam%20classification%20using%20LSTM/SMS_Spam_Classifier_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTMs
from tensorflow.keras.layers import Dense

In [ ]:
message=pd.read_csv("https://raw.githubusercontent.com/SaurabhSRP/04-NLP-based-Projects/main/SMS%20Spam%20classification%20using%20LSTM/SMSSpamCollection",sep='\t',names=["lable","message"])
message.head()

lable                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
message.shape


(5572, 2)

In [ ]:
map={'ham':0,'spam':1}
message['lable']=message['lable'].map(map)

#**Feature Engineering**
* Stop words
* lemmatization
* Word Embedding


In [ ]:
import nltk
import re
from nltk.corpus import stopwords

nltk.download('stopwords')

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
corpus=[]
for i in range(0, len(message)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', message['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
8

In [ ]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [ ]:
voc_size=5000
onehot_repr=[one_hot(words,voc_size) for words in corpus]
onehot_repr

[[3271,
  63,
  4976,
  2071,
  1928,
  857,
  4520,
  2498,
  4116,
  388,
  2541,
  3247,
  3205,
  947,
  4311,
  3977],
 [3942, 652, 1815, 284, 2137, 33],
 [195,
  4955,
  634,
  219,
  1894,
  3750,
  1988,
  2427,
  1697,
  1746,
  4441,
  2563,
  3750,
  60,
  4955,
  1154,
  201,
  1754,
  246,
  3058,
  1828],
 [2137, 3274, 4694, 3970, 1656, 2137, 3058, 2839, 4694],
 [4213, 96, 3271, 4160, 237, 2812, 1540],
 [4041,
  1247,
  3655,
  1699,
  2248,
  4987,
  2041,
  346,
  19,
  1520,
  3942,
  4334,
  201,
  4975,
  4316,
  233],
 [2930, 585, 2041, 1205, 1680, 2041, 4341, 232],
 [4281,
  1095,
  1629,
  1629,
  4080,
  1530,
  3892,
  3265,
  3313,
  4433,
  2455,
  4778,
  2531,
  3246,
  4433],
 [4023,
  3920,
  4006,
  679,
  1046,
  2648,
  4598,
  3565,
  90,
  104,
  90,
  1450,
  1708,
  2905,
  3510],
 [2832,
  3628,
  2137,
  2487,
  620,
  1900,
  356,
  1681,
  2832,
  4297,
  195,
  104,
  2832,
  1900,
  2744,
  195],
 [1122, 2343, 2676, 1167, 4180, 3441, 2582, 238

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  947 4311 3977]
 [   0    0    0 ...  284 2137   33]
 [4955  634  219 ...  246 3058 1828]
 ...
 [   0    0    0 ... 3734 1400 4562]
 [   0    0    0 ... 1226 2137  195]
 [   0    0    0 ... 4502 3922 1879]]


#**Building LSTM model**

In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


#**Independent and dependent Features**

In [ ]:
X=np.array(embedded_docs)
y=np.array(message['lable'])


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=2)

#**Model training**

In [ ]:
### Finally Training
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
59/59 [==============================] - 3s 43ms/step - loss: 1.9529e-04 - accuracy: 1.0000 - val_loss: 0.1622 - val_accuracy: 0.9777
Epoch 2/20
59/59 [==============================] - 2s 40ms/step - loss: 1.5029e-04 - accuracy: 1.0000 - val_loss: 0.1467 - val_accuracy: 0.9799
Epoch 3/20
59/59 [==============================] - 2s 41ms/step - loss: 1.7261e-04 - accuracy: 1.0000 - val_loss: 0.1519 - val_accuracy: 0.9788
Epoch 4/20
59/59 [==============================] - 2s 40ms/step - loss: 1.0376e-04 - accuracy: 1.0000 - val_loss: 0.1700 - val_accuracy: 0.9782
Epoch 5/20
59/59 [==============================] - 2s 41ms/step - loss: 1.0039e-04 - accuracy: 1.0000 - val_loss: 0.1689 - val_accuracy: 0.9788
Epoch 6/20
59/59 [==============================] - 2s 40ms/step - loss: 8.3881e-05 - accuracy: 1.0000 - val_loss: 0.1554 - val_accuracy: 0.9804
Epoch 7/20
59/59 [==============================] - 2s 40ms/step - loss: 6.8273e-05 - accuracy: 1.0000 - val_loss: 0.1720 - val_ac

In [ ]:
y_pred=(model.predict(X_test) > 0.5).astype("int32")

58/58 [==============================] - 0s 7ms/step


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1578,    8],
       [  31,  222]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9787928221859706